#PRD
server: 
  servlet:
    context-path: /scs4app
  port: 8082
    
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: ["*"]

info:
   app:
     version: v1.0.0
     name: scs4app    
     
#mybatis
mybatis:
  #默认寻找位置为包名同级的resource目录
  mapper-locations: classpath:mapper/**/*.xml,classpath*:mapper/**/*.xml
  configuration:
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#page helper
pagehelper:
  helperDialect: oracle
  reasonable: false
  supportMethodsArguments: true
  closeConn: true
  pageSizeZero: true
  
#db
spring:
  datasource:
      jndi-name: jdbc/SCS5050

logging:
  config: classpath:log4j2.xml

#okhttp
okhttp3:
  connectTimeout: 60000
  readTimeout: 60000
  writeTimeout: 60000
  maxIdleConnections: 60
  keepAliveDuration: 60000
