package com.saic.ndms.sdi.common.dto;

public class CodeLabelResponse {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.CODE_ID
	 *
	 * @mbggenerated
	 */
	private String label;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.TYPE
	 *
	 * @mbggenerated
	 */
	private String value;

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	
}