package com.saic.ndms.sdi.common.dto;

import java.util.Date;

public class CodeResponse {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.CODE_ID
	 *
	 * @mbggenerated
	 */
	private Long codeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.TYPE
	 *
	 * @mbggenerated
	 */
	private Short type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.TYPE_NAME
	 *
	 * @mbggenerated
	 */
	private String typeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.CODE_EN_DESC
	 *
	 * @mbggenerated
	 */
	private String codeEnDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.CODE_CN_DESC
	 *
	 * @mbggenerated
	 */
	private String codeCnDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.NUM
	 *
	 * @mbggenerated
	 */
	private Integer num;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.STATUS
	 *
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.CREATE_BY
	 *
	 * @mbggenerated
	 */
	private Long createBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.UPDATE_BY
	 *
	 * @mbggenerated
	 */
	private Long updateBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.UPDATE_DATE
	 *
	 * @mbggenerated
	 */
	private Date updateDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.ORG_CODE
	 *
	 * @mbggenerated
	 */
	private String orgCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TC_CODE.VALUE
	 *
	 * @mbggenerated
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.CODE_ID
	 *
	 * @return the value of TC_CODE.CODE_ID
	 *
	 * @mbggenerated
	 */
	public Long getCodeId() {
		return codeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.CODE_ID
	 *
	 * @param codeId
	 *            the value for TC_CODE.CODE_ID
	 *
	 * @mbggenerated
	 */
	public void setCodeId(Long codeId) {
		this.codeId = codeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.TYPE
	 *
	 * @return the value of TC_CODE.TYPE
	 *
	 * @mbggenerated
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.TYPE
	 *
	 * @param type
	 *            the value for TC_CODE.TYPE
	 *
	 * @mbggenerated
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.TYPE_NAME
	 *
	 * @return the value of TC_CODE.TYPE_NAME
	 *
	 * @mbggenerated
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.TYPE_NAME
	 *
	 * @param typeName
	 *            the value for TC_CODE.TYPE_NAME
	 *
	 * @mbggenerated
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName == null ? null : typeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.CODE_EN_DESC
	 *
	 * @return the value of TC_CODE.CODE_EN_DESC
	 *
	 * @mbggenerated
	 */
	public String getCodeEnDesc() {
		return codeEnDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.CODE_EN_DESC
	 *
	 * @param codeEnDesc
	 *            the value for TC_CODE.CODE_EN_DESC
	 *
	 * @mbggenerated
	 */
	public void setCodeEnDesc(String codeEnDesc) {
		this.codeEnDesc = codeEnDesc == null ? null : codeEnDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.CODE_CN_DESC
	 *
	 * @return the value of TC_CODE.CODE_CN_DESC
	 *
	 * @mbggenerated
	 */
	public String getCodeCnDesc() {
		return codeCnDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.CODE_CN_DESC
	 *
	 * @param codeCnDesc
	 *            the value for TC_CODE.CODE_CN_DESC
	 *
	 * @mbggenerated
	 */
	public void setCodeCnDesc(String codeCnDesc) {
		this.codeCnDesc = codeCnDesc == null ? null : codeCnDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.NUM
	 *
	 * @return the value of TC_CODE.NUM
	 *
	 * @mbggenerated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.NUM
	 *
	 * @param num
	 *            the value for TC_CODE.NUM
	 *
	 * @mbggenerated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.STATUS
	 *
	 * @return the value of TC_CODE.STATUS
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.STATUS
	 *
	 * @param status
	 *            the value for TC_CODE.STATUS
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.CREATE_BY
	 *
	 * @return the value of TC_CODE.CREATE_BY
	 *
	 * @mbggenerated
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.CREATE_BY
	 *
	 * @param createBy
	 *            the value for TC_CODE.CREATE_BY
	 *
	 * @mbggenerated
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.CREATE_DATE
	 *
	 * @return the value of TC_CODE.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.CREATE_DATE
	 *
	 * @param createDate
	 *            the value for TC_CODE.CREATE_DATE
	 *
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.UPDATE_BY
	 *
	 * @return the value of TC_CODE.UPDATE_BY
	 *
	 * @mbggenerated
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.UPDATE_BY
	 *
	 * @param updateBy
	 *            the value for TC_CODE.UPDATE_BY
	 *
	 * @mbggenerated
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.UPDATE_DATE
	 *
	 * @return the value of TC_CODE.UPDATE_DATE
	 *
	 * @mbggenerated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.UPDATE_DATE
	 *
	 * @param updateDate
	 *            the value for TC_CODE.UPDATE_DATE
	 *
	 * @mbggenerated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.ORG_CODE
	 *
	 * @return the value of TC_CODE.ORG_CODE
	 *
	 * @mbggenerated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.ORG_CODE
	 *
	 * @param orgCode
	 *            the value for TC_CODE.ORG_CODE
	 *
	 * @mbggenerated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TC_CODE.VALUE
	 *
	 * @return the value of TC_CODE.VALUE
	 *
	 * @mbggenerated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TC_CODE.VALUE
	 *
	 * @param value
	 *            the value for TC_CODE.VALUE
	 *
	 * @mbggenerated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}
}